### ISSUE TITLE
Different directions on the projectguide page, incorrect ng-repeat placement

### ISSUE THREAD

**Issue by gnordstrom** [DevMountain/angular-friends#19]
So the link you're taken to from the class schedule is http://projectguide.devmounta.in/#/angular-friends, which has different directions compared to the readme on github. I think the github readme is the one to go with.

On the github readme file, at the bottom of section 6 and the bottom of section 7, it says to add another ng-repeat to the <ul> tag, which is incorrect and repeats the entire list 28 times. The only ng-repeat should be added to the <li> tag

**Comment by asBrettisay** [comment]
Hey @gnordstrom, I'm a bit confused, because the project guide should be **exactly** what is in the readme. As far as I can tell that is the case. Am I missing something?

Also, your `<ul>` and `<li>` tags were swallowed by github, you need to put them inside \`\`.

**Comment by asBrettisay** [comment]
Either way I think you are correct, this is a typo. I'll fix it.

**Comment by asBrettisay** [comment]
Fixed by #20

**Comment by gnordstrom** [comment]
@asBrettisay Jeremy just gave me a tour of how to properly use the project guide, so that was my mistake as they are indeed identical. Lots of students made the same mistake I did (not clicking "More" to see the rest) so I'll address it in class today. Thanks!
